channels:
    - conda-forge
name:
   matchmaker_env
dependencies:
    - python==3.11
    - tifffile
    - z5py
    - tqdm

    - tmux
    - vim
    - git
    - git-lfs

    - scikit-image
    # - optuna
    # - proxsuite
    - cvxpy
    - transforms3d

    - ipykernel
    - seaborn
    - matplotlib
    - cupy

    - mobie_utils

    - pytest

    - pip
    - pip:
        - itk-elastix
    #    - cupy
    #    - probreg
        - pyscipopt
        - click
        - pyyaml
        - itk
        - snakemake
        - probreg
        - -e .
