fixed_image:
  source_path: "examples/data/platy1_muscles_stardist_fixed.tif"
  path: "examples/data/deformed_data/platy1_muscles_stardist_fixed_rotated.tif"
  output_name: "fixed_image"
  x_res: 1
  y_res: 1
  z_res: 1

moving_image:
  path: "examples/data/deformed_data/platy1_muscles_stardist_rigid.tif"
  output_name: "moving_image"
  x_res: 1
  y_res: 1
  z_res: 1
  ref_path: "examples/data/test_data/moving_rigid_aligned.tif"
  ref_url: "https://github.com/kreshuklab/matchmaker/releases/download/test_data-v0.3/moving_rigid_aligned.tif"

log_dir: "data/test_rigid_registration"
final_transform_path: "data/test_rigid_registration/final_transform.json"

prealignment:
  axis_orientation: "auto"

coherent_point_drift:
  w: 0.00001
  lmd: 0.1
  beta: 100
  maxiter: 10 # Low for debugging purpose, should be 100-150

ILP:
  min_neighbours: 10
  max_dist: 30

mobie_export: True
semantic_seg: True
mobie_dataset_name: "platy1_muscles_stardist"
