fixed_image:
  path: "examples/data/platy1_muscles_stardist_fixed.tif"
  x_res: 1
  y_res: 1
  z_res: 1

moving_image:
  path: "examples/data/platy1_muscles_stardist_moving.tif"
  x_res: 1
  y_res: 1
  z_res: 1

log_dir: "data/test_registration"
final_transform_path: "data/test_registration/final_transform.json"

coherent_point_drift:
  w: 0.00001
  lmd: 0.1
  beta: 100
  maxiter: 10 # Low for debugging purpose, should be 100-150

ILP:
  min_neighbours: 30
  max_dist: 30


# mobie_export = true # NOTE: do we want that flag?
mobie_dataset_name: "platy1_muscles_stardist"